---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hotelsunplaza/pragatikurtis.com/
    - /bin/cp -Rf backend $DEPLOYPATH/
    - /bin/cp -Rf frontend/dist/* $DEPLOYPATH/
    - /bin/cp -f frontend/dist/.htaccess $DEPLOYPATH/
